output "provider_id" {
  description = "Authentik OAuth2 provider ID."
  value       = authentik_provider_oauth2.this.id
}

output "application_id" {
  description = "Authentik application ID."
  value       = authentik_application.this.id
}

output "client_id" {
  description = "OIDC client ID (same as slug)."
  value       = authentik_provider_oauth2.this.client_id
}

output "client_secret" {
  description = "OIDC client secret generated by Authentik."
  value       = authentik_provider_oauth2.this.client_secret
  sensitive   = true
}
